development: &development
  adapter: postgresql
  database: 
  pool: 5
  timeout: 5000
  username: 
  password: 
  host: 
  encoding: 

staging:
  <<: *development
  
integration:
  <<: *development

test: 
  <<: *development

production:
  <<: *development

cucumber:
  <<: *development
